### ISSUE TITLE
all keys are treated as strings?

### ISSUE THREAD

**Issue by deltazita** [arunbear/Tree-RB#1]
I created a RBT with numbers as keys and min/max functions do not work well
For example, 'min' considers 7094 < 710
Apologies, I just saw that you can define your own comparator

**Comment by arunbear** [comment]
Yes, because the tree allows values to be anything, so lexical ordering by default seemed like the sensible thing to do.

**Comment by arunbear** [comment]
Yes, because the tree allows values to be anything, so lexical ordering by default seemed like the sensible thing to do.

**Comment by arunbear** [comment]
Yes, because the tree allows values to be anything, so lexical ordering by default seemed like the sensible thing to do.
